#
# This workflow calls the main distribution pipeline from DuckDB to build, test and (optionally) release the extension
#
name: Main Extension Distribution Pipeline
on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

jobs:
  duckdb-next-build:
    name: Build extension binaries
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@main
    with:
      duckdb_version: main
      ci_tools_version: main
      extension_name: avro

  duckdb-stable-build:
    name: Build extension binaries
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@v1.1.3
    with:
      duckdb_version: v1.1.3
      ci_tools_version: v1.1.3
      extension_name: avro
      exclude_archs: "wasm_mvp;wasm_eh;wasm_threads;windows_amd64_rtools"

  duckdb-stable-deploy:
    name: Deploy extension binaries
    needs: duckdb-stable-build
    uses: ./.github/workflows/_extension_deploy.yml
    secrets: inherit
    with:
      duckdb_version: v1.1.3
      extension_name: avro
      exclude_archs: "wasm_mvp;wasm_eh;wasm_threads;windows_amd64_rtools"
      deploy_latest: ${{ startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main' }}


  windows:
    name: Windows
    runs-on: windows-2019
    env:
      VCPKG_TOOLCHAIN_PATH: ${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
      VCPKG_TARGET_TRIPLET: x64-windows-static-md
      BUILD_SHELL: '0'
      DUCKDB_PLATFORM: windows_amd64


    steps:
      - name: Keep \n line endings
        shell: bash
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf



      - uses: actions/checkout@v4
        name: Checkout current repository
        with:
          fetch-depth: 0
          submodules: 'true'

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'


      - uses: actions/checkout@v4
        name: Checkout Extension CI tools
        with:
          path: 'extension-ci-tools'
          ref: v1.1.3



      - name: Setup Ccache
        uses: hendrikmuhs/ccache-action@main
        continue-on-error: true


      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11.1
        with:
          vcpkgGitCommitId: a1a1cbc975abf909a6c8985a6a2b8fe20bbd9bd6
          vcpkgGitURL: "https://github.com/microsoft/vcpkg.git"

      - name: Run configure
        shell: bash
        env:
          DUCKDB_PLATFORM: windows_amd64
          DUCKDB_PLATFORM_RTOOLS: 0
          DUCKDB_GIT_VERSION: v1.1.3
        run: |
          make configure_ci

      - name: Build extension
        env:
          DUCKDB_PLATFORM: windows_amd64
          DUCKDB_PLATFORM_RTOOLS: 0
        run: |
          make release

      - name: list
        if: failure()
        run: |
          find build/release
